create table "keep_alive"(
  id bigint generated by default as identity,
  name text null default ''::text,
  random uuid null default gen_random_uuid(),
  constraint "keep_alive_pkey" primary key (id)
);

alter table public.keep_alive enable row level security;

create policy "Everyone can view keep alive" on public.keep_alive
  for select
    using (true);

